###Register to see if its working
POST http://localhost:6000/auth/register
Content-Type: application/json

{
    "name": "Joao",
    "email": "joao@gmail.com",
    "password": "98765"
}


###Login to see if its working
POST http://localhost:6000/auth/login
Content-Type: application/json

{
    "email": "davidSA@gmail.com",
    "password": "123456"
}


###Get user Details to see if its working
GET http://localhost:6000/user/info
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ4NDIxLCJleHAiOjE3NTMwMzQ4MjF9.5G6fy9w9I6J-BrdsXUJOhL_whDzuVn9N-WlUNDbxcI0
Content-Type: application/json


### Deleting the user
DELETE  http://localhost:6000/user/delete
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ4NDIxLCJleHAiOjE3NTMwMzQ4MjF9.5G6fy9w9I6J-BrdsXUJOhL_whDzuVn9N-WlUNDbxcI0
Content-Type: application/json


###Update user to see if its working
PUT http://localhost:6000/user/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ4NDIxLCJleHAiOjE3NTMwMzQ4MjF9.5G6fy9w9I6J-BrdsXUJOhL_whDzuVn9N-WlUNDbxcI0
Content-Type: application/json

{
    "name": "DavidSA",
    "email": "davidSA@gmail.com"
}


### Cheking this months expenses
GET http://localhost:6000/expenses/current-month
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNjI2ODIyLCJleHAiOjE3NTM3MTMyMjJ9.x3Fw9FDWhidvKlEYUHNg-SFsf-6xuAKRSq-RbLKJcnQ
Content-Type: application/json

###Getting all expenses 
GET http://localhost:6000/expenses/all-expenses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNjI2ODIyLCJleHAiOjE3NTM3MTMyMjJ9.x3Fw9FDWhidvKlEYUHNg-SFsf-6xuAKRSq-RbLKJcnQ
Content-Type: application/json


###Adding expenses 
POST http://localhost:6000/expenses/add-expense
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNjE5MTI4LCJleHAiOjE3NTM3MDU1Mjh9.mbGPHAu7k3dFwurJgGs0O4A4fY_dDPkQLR1ecU5TaJE
Content-Type: application/json

{
    "description": "testeParaAquitetura",
    "price": 2.00,
    "category": "testar",
    "date": "2025-01-11T00:00:00.000Z"
}

###Getting a specific expenses by putting it in the url
GET http://localhost:6000/expenses/one-expense/30
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNjI2ODIyLCJleHAiOjE3NTM3MTMyMjJ9.x3Fw9FDWhidvKlEYUHNg-SFsf-6xuAKRSq-RbLKJcnQ

###Deleting expenses
DELETE http://localhost:6000/expenses/delete-expense/27
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNjI2ODIyLCJleHAiOjE3NTM3MTMyMjJ9.x3Fw9FDWhidvKlEYUHNg-SFsf-6xuAKRSq-RbLKJcnQ


###Update expenses
PUT http://localhost:6000/expenses/update-expense/26
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNjI2ODIyLCJleHAiOjE3NTM3MTMyMjJ9.x3Fw9FDWhidvKlEYUHNg-SFsf-6xuAKRSq-RbLKJcnQ
Content-Type: application/json

{
    "description": "testeParaAquitetura",
    "price": 12.00,
    "category": "testar",
    "date": "2025-01-11T00:00:00.000Z"
}
