###Register to see if its working
POST http://localhost:6000/auth/register
Content-Type: application/json

{
    "name": "David",
    "email": "david@gmail.com",
    "password": "123456"
}


###Login to see if its working
POST http://localhost:6000/auth/login
Content-Type: application/json

{
    "email": "davidSA@gmail.com",
    "password": "123456"
}


###Get user Details to see if its working
GET http://localhost:6000/user/info
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ4NDIxLCJleHAiOjE3NTMwMzQ4MjF9.5G6fy9w9I6J-BrdsXUJOhL_whDzuVn9N-WlUNDbxcI0
Content-Type: application/json


### Deleting the user
DELETE  http://localhost:6000/user/delete
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ4NDIxLCJleHAiOjE3NTMwMzQ4MjF9.5G6fy9w9I6J-BrdsXUJOhL_whDzuVn9N-WlUNDbxcI0
Content-Type: application/json


###Update user to see if its working
PUT http://localhost:6000/user/edit
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUyOTQ4NDIxLCJleHAiOjE3NTMwMzQ4MjF9.5G6fy9w9I6J-BrdsXUJOhL_whDzuVn9N-WlUNDbxcI0
Content-Type: application/json

{
    "name": "DavidSA",
    "email": "davidSA@gmail.com"
}


### Cheking this months expenses
GET http://localhost:6000/expenses/current-month
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNTQ0OTQwLCJleHAiOjE3NTM2MzEzNDB9.wWG4Qobj0tc6zNsgUfBMKq7RqM9A755nHqANAXrp9FM
Content-Type: application/json

###Getting all expenses 
GET http://localhost:6000/expenses/all-expenses
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNTQ0OTQwLCJleHAiOjE3NTM2MzEzNDB9.wWG4Qobj0tc6zNsgUfBMKq7RqM9A755nHqANAXrp9FM
Content-Type: application/json


###Adding expenses 
POST http://localhost:6000/expenses/add-expense
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzMzc0NzQyLCJleHAiOjE3NTM0NjExNDJ9.eyf5tfi1jgVUZCU3JvCY7TkFUQI9q5TRl0VYJWZTsVg
Content-Type: application/json

{
    "description": "Continente",
    "price": 20.01,
    "category": "Entretenimento",
    "date": "2025-06-13T00:00:00.000Z"
}

###Getting a specific expenses by putting it in the url
GET http://localhost:6000/expenses/one-expense/12
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzMzc0NzQyLCJleHAiOjE3NTM0NjExNDJ9.eyf5tfi1jgVUZCU3JvCY7TkFUQI9q5TRl0VYJWZTsVg

###Deleting expenses
DELETE http://localhost:6000/expenses/delete-expense/21
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNDM4OTQ5LCJleHAiOjE3NTM1MjUzNDl9.hU2nuH0FwFneicpY5SLJbJQXuKnIlWul-An7C2k0MZM


###Update expenses
PUT http://localhost:6000/expenses/delete-expense/22
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzUzNTQ0OTQwLCJleHAiOjE3NTM2MzEzNDB9.wWG4Qobj0tc6zNsgUfBMKq7RqM9A755nHqANAXrp9FM
Content-Type: application/json

{
    "description": "Continente",
    "price": "20.01",
    "category": "Entretenimento",
    "date": "2025-06-13T00:00:00.000Z",
}
